### ISSUE TITLE
Extensible Controls

### ISSUE THREAD

**Issue by mihirpatel83** [sethsandaru/vue-form-builder#10]
Is it possible to add more customized controls like Address which is a group of few html elements alone with controls like Rating control, Captcha, Email, URL etc ?
I can see it's written extensible but just wanted to make sure before I go ahead an use your component.

**Comment by sethsandaru** [comment]
Yeah, the documentation is not finished yet. I'm still working on it.

**Comment by petargeorgiev123** [comment]
gi @sethsandaru any news about the documentation about adding custom controls you promised? We are not finding a way to extend and add proper controls. 
Will appreciate some help. Thanks.

**Comment by sethsandaru** [comment]
Hello @petargeorgiev123 ,

Here is the page https://github.com/sethsandaru/vue-form-builder/wiki/Extend-a-new-Control, I probably forgot about this. Let me finish the page. In the meanwhile, you can read the concept to see how it works. 

Thank you for reminding me. Sorry...

**Comment by sethsandaru** [comment]
Hey guys,

Just let you know that I finished the documentation. Check it out. Thank you.
