### ISSUE TITLE
Uncaught TypeError: Cannot set property 'TimePicker' of undefined

### ISSUE THREAD

**Issue by srober12** [sethsandaru/vue-form-builder#13]
Grabbed the latest version from NPM and when I try to load either of the dist scripts it throws the error in the title. I'm probably missing something obvious, but havent figured it out yet.

Vue.js v2.5.16
jQuery v3.3.1
jQuery UI - v1.12.1 
Bootstrap v4.1.3

```` html
<script type="module" src="/lib/v-form-builder/vue-form-builder.min.js"></script>
`````
or 

```` html
<script type="text/javascript" src="/lib/v-form-builder/dist/vue-form-builder.browser.min.js"></script>
````

**Comment by sethsandaru** [comment]
Hi there,

Currently the library cannot be able to imported directly by using script src thing. You have to create your own webpack project (with Vue) and build it to use. You can use **Vue Simple Project** to get started (easy and small)

For the `vue-form-builder.browser.min.js`, I'm still working on that. 

Thank you!
