### ISSUE TITLE
Jquery not loading 

### ISSUE THREAD

**Issue by Devin0231577** [sethsandaru/vue-form-builder#15]
TypeError: $(...).sortable is not a function

**Comment by Muneera-Salah** [comment]
me too
![image](https://user-images.githubusercontent.com/3780724/60551524-32580400-9d34-11e9-85b4-5939644dbbf5.png)

**Comment by chaitya1001** [comment]
I am having same problem.

**Comment by sethsandaru** [comment]
Hey guys, 

My old-version demo is still working properly here: http://vue-form-builder.sethphat.com/#/template/config/.

Could you guys please give me a snippet of your code to check it out?

Thanks

**Comment by V-Orbit** [comment]
> 
> 
> me too
> ![image](https://user-images.githubusercontent.com/3780724/60551524-32580400-9d34-11e9-85b4-5939644dbbf5.png)

we had this issue also

**Comment by sethsandaru** [comment]
Hey guys,

I'm very sorry about the inactivity of the library. I already made a plan to rebuild the Vue Form Builder again. Main reasons:

- The codebase is not clean enough (yes, more than 1 year already), even I feel bad and saw that it's hard to maintain
- A lot of dependencies, I need to reduce it, it made the form itself too heavy (2M)
- Prevent to export any unnecessary variables/functions and prevent to use the `window` object
- A lot of problems in the current form.
- ...

You can see more detail in the main repository README. Until that, I think I won't support any old problems and hope you guys wait for the new version instead. The current one looks very unstable (from then to now).

Thank you for your support and a big apology from me!
