### ISSUE TITLE
required not working on inputs other than text inputs

### ISSUE THREAD

**Issue by Abouhassane** [sethsandaru/vue-form-builder#19]
Hi,

As the title dictates, required restriction does not work on the inputs except the text input.

Can you please verify wether this is an issues or i'm doing something wrong?

**Comment by sethsandaru** [comment]
Hi friend,

Vue-Form-Builder@2.0.0 has been released. Check it out.

P/s: I closed this issue because it's not related to Vue-Form-Builder@2.0.0
Thanks.
