### ISSUE TITLE
Overwriting window._

### ISSUE THREAD

**Issue by frizikk** [sethsandaru/vue-form-builder#21]
https://github.com/sethsandaru/vue-form-builder/blob/cf15a8416a23744369e5f8ac97920d56682864b7/src/config/loader.js#L31

I think this shouldn't be done like that. Many people use window._ for lodash or other libraries. 
And if I import your package you overwrite my variable.

**Comment by sethsandaru** [comment]
Hello @frizikk ,

Maybe I should describe more about the libraries that Vue-Form-Builder depend on.  
My form using "underscore" as one of the main libraries. Right now if you do a fork and change to lodash it will break (probably).

I might to extend it to support the lodash later. For now is no. Sorry.

**Comment by frizikk** [comment]
@sethsandaru 

I had on my mind you should create your own namespace for underscore. (in example window.sethsandaru_underscore). To let people assign **window._**
