### ISSUE TITLE
FontAwesome owerwriting

### ISSUE THREAD

**Issue by frizikk** [sethsandaru/vue-form-builder#22]
In my current project I use FonAwesome loaded by css file. 
When I install your package it overwrite my FontAwesome icons, and they stop showing.

![Zrzut ekranu z 2019-10-30 17-49-04](https://user-images.githubusercontent.com/4850809/67879960-22173080-fb3e-11e9-8eec-8c4a885d0216.png)

**Comment by sethsandaru** [comment]
Hi @frizikk ,

For this problem. I think I need to create an `option` to define which FontAwesome that we want to use:

- FontAwesome imported in HTML (`<link ... />`)
- FontAwesome in Webpack

Noted. Will update it.

Thank you for reporting.

**Comment by onix-dev** [comment]
the same issue... conflict with npm version of fontawesome

**Comment by sethsandaru** [comment]
Hi friend,

Vue-Form-Builder@2.0.0 has been released. Check it out.

P/s: I closed this issue because it's not related to Vue-Form-Builder@2.0.0
Thanks.
