### ISSUE TITLE
Can't built via npm run build-bundle

### ISSUE THREAD

**Issue by eok8177** [sethsandaru/vue-form-builder#23]
When I build and use it my Vue project, get errors: 

TypeError: $(...).sortable is not a function
TypeError: $(...).draggable is not a function

Work with files /dist/ only from repo

**Comment by sethsandaru** [comment]
Hi @eok8177 

Have you run "npm install" yet before "npm run build"?

Thank you

**Comment by eok8177** [comment]
Hi! Yes

![image](https://user-images.githubusercontent.com/8864590/68004407-103aa800-fc7a-11e9-9648-4963b325226c.png)
![image](https://user-images.githubusercontent.com/8864590/68004427-28122c00-fc7a-11e9-992b-d546b38adfc4.png)

node -v    v8.10.0
npm -v     6.12.1
"os":"linux","arch":"x64"

**Comment by eok8177** [comment]
if I run directly via index.html
![image](https://user-images.githubusercontent.com/8864590/68004763-6bb96580-fc7b-11e9-8322-5fbfc04a7e71.png)

get this error
![image](https://user-images.githubusercontent.com/8864590/68004732-56443b80-fc7b-11e9-80d7-576108e8bf61.png)

**Comment by eok8177** [comment]
Can You explain me, how use it in project folder. 
Not in node_modules folder. 
I want change some design and functional.

**Comment by eok8177** [comment]
Problem was: 
when I run npm install in node_modules folder
I get this errors

Ok, only if copy builded library into folder node_modules
