### ISSUE TITLE
Why did you remove and did not add a props for stylesheet? 

### ISSUE THREAD

**Issue by isikhi** [sethsandaru/vue-form-builder#24]
> Note: From the version 1.2.0 to above, I don't import bootstrap 4 stylesheet into the bundle, you should include your own bootstrap 4 stylesheet in order to get both of GUI & Template working normally.

Hi i wonder why you did not add stylesheet on props? I want to bind bootstrap on my local and that is a little bit buggy because my stylesheet scopes are diffrent

**Comment by sethsandaru** [comment]
Hi friend,

Vue-Form-Builder@2.0.0 has been released. Check it out.

P/s: I closed this issue because it's not related to Vue-Form-Builder@2.0.0
Thanks.
