### ISSUE TITLE
setValue() and v-model cannot change number control value

### ISSUE THREAD

**Issue by yoyoyosheep** [sethsandaru/vue-form-builder#25]
How to repro:
1. set number control value by setValue or data binding with js code, for example 80, you will see that it shows 80
2. get number control value by getValue or data binding with js code, you will find the value is 0
3. change value on web page, for example +1, then get value again, now the result is right, 81
It's so strange that number control shows 80 at first since the value I can get is 0

**Comment by sethsandaru** [comment]
Hi friend,

Vue-Form-Builder@2.0.0 has been released. Check it out.

P/s: I closed this issue because it's not related to Vue-Form-Builder@2.0.0
Thanks.
