### ISSUE TITLE
Translatable forms

### ISSUE THREAD

**Issue by bajki** [sethsandaru/vue-form-builder#26]
Hi, how to achieve to have same form with multiple languages?

If i create  
`<form-builder type="gui"  :form="fields"   v-model="language.en"   ref="FormGUIEn" ></form-builder>`
`<form-builder type="gui"  :form="fields"   v-model="language.de"   ref="FormGUIDe" ></form-builder>
`
If i write in EN it updates DE model and vice versa.

I need translatable fields but dont know how to do it.

**Comment by sethsandaru** [comment]
Hi @bajki ,

How about :

```html
<form-builder type="gui" :form="fields" v-model="language.en" ref="FormGUIEn" v-if="currentLanguage == 'en'" ></form-builder>
```

The translatable field/form is one of my biggest plans at the moment, including update again a whole project. Since I've already made a simple translatable field in my previous project here: https://github.com/sethsandaru/laravel-multilingual

**Comment by sethsandaru** [comment]
Hi friend,

Vue-Form-Builder@2.0.0 has been released. Check it out.

P/s: I closed this issue because it's not related to Vue-Form-Builder@2.0.0
Thanks.
