### ISSUE TITLE
Minimal Demo

### ISSUE THREAD

**Issue by jakeaston** [sethsandaru/vue-form-builder#28]
Do you have any plans to add a minimal demo to allow easier porting to Node or other server enviroments? 

Thanks

**Comment by sethsandaru** [comment]
Hi friend,

Sure, but the main idea is simply to understand. You created a form and got the `JSON` configuration. Simply convert it to `JSON String` and then put it to the database.

Every time you want to use the form, retrieve the configuration from the database then parse the JSON String to Object and pass it to the Vue Form. :D
