### ISSUE TITLE
_.deepExtend is not a function.

### ISSUE THREAD

**Issue by rachitpant** [sethsandaru/vue-form-builder#29]
I decided to give this a try on my project. When I click preview , I get this error.
![image](https://user-images.githubusercontent.com/1474415/78605807-36b4ce80-782a-11ea-88af-d21e8002a12d.png)
I am getting this same error when I click section config. After this, I am not able to close the preview section , basically the screen becomes unresponsive.

**Comment by rachitpant** [comment]
Not sure if this is happening because I am using lodash (_) in the application in other pages.

**Comment by sethsandaru** [comment]
One of my dependencies is lodash which has `_.deepExtend` method. I think I'm gonna remove lodash out of my dependencies soon. 

Thanks for reporting!

**Comment by rachitpant** [comment]
I think over here you are trying to mixin the method using `underscoreDeepExtend`. Something else I want to point out is that its not a good idea to pollute global window namespace.

**Comment by rockyfeller** [comment]
Please what is the way around this at the moment?

**Comment by rachitpant** [comment]
I spent a lot of time trying to fix bugs , it wasnt worth the time, our
company decided to go with surveyjs.io when we tackle it. Its lot more
refined as has a lot more features.

**Comment by sethsandaru** [comment]
Hey guys,

I'm very sorry about the inactivity of the library. I already made a plan to rebuild the Vue Form Builder again. Main reasons:

- The codebase is not clean enough (yes, more than 1 year already), even I feel bad and saw that it's hard to maintain
- A lot of dependencies, I need to reduce it, it made the form itself too heavy (2M)
- Prevent to export any unnecessary variables/functions and prevent to use the `window` object
- A lot of problems in the current form.
- ...

You can see more detail in the main repository README. Until that, I think I won't support any old problems and hope you guys wait for the new version instead. The current one looks very unstable (from then to now).

Thank you for your support and a big apology from me!
