### ISSUE TITLE
A demo would be nice

### ISSUE THREAD

**Issue by xvaara** [sethsandaru/vue-form-builder#3]
As the title says.

**Comment by cutemonster** [comment]
exactly

**Comment by sethsandaru** [comment]
Yeah, I'm doing it right now, Thanks :D

**Comment by sethsandaru** [comment]
You can find demo here, check it out!

Demo Online: http://vue-form-builder.sethphat.com
Demo Project: https://github.com/sethsandaru/demo-vue-form-builder
