### ISSUE TITLE
npm: 1.4.1-rc2

### ISSUE THREAD

**Issue by onix-dev** [sethsandaru/vue-form-builder#32]
Please push source of the latest version... I can't find any branch related to the version from npm... 
The latest avalible source has conflict with bootstrap, dom... but looks like it's fixid in 1.4.1-rc2.. 
The source code in the npm package also out of date and build folder include a newer version.

**Comment by sethsandaru** [comment]
Hi friend,

Vue-Form-Builder@2.0.0 has been released. Check it out.

P/s: I closed this issue because it's not related to Vue-Form-Builder@2.0.0
Thanks.
