### ISSUE TITLE
Release date for v2.0?

### ISSUE THREAD

**Issue by thegoatherder** [sethsandaru/vue-form-builder#33]
Fantastic work! Really loving the v2.0.0 it meets a lot of our requirements.
We might need to extend it to include more input validation options and perhaps we can help you in this area by submitting PRs?

We have a burning requirement to use v2.0 in a project, but am conscious that it's still undergoing regular change - do you have a release date scheduled, even if it's a ballpark? Is there much work left to do?

Thanks!

**Comment by sethsandaru** [comment]
Hello @thegoatherder ,

Yes sure, but I think let the v2.0.0 released first and then we can focus on more validations, features,...

Currently, Vue-Form-Builder v2.0.0 is in the testing phase, all the planned stuff is ready. I'm optimistic to release it on next week or even sooner :D

Thank you. Stay tuned.

**Comment by sethsandaru** [comment]
Hi friend,

Vue-Form-Builder@2.0.0 has been released. Check it out.

P/s: I closed this issue because it's not related to Vue-Form-Builder@2.0.0
Thanks.
