### ISSUE TITLE
TypeError: _.deepExtend is not a function

### ISSUE THREAD

**Issue by ronny35** [sethsandaru/vue-form-builder#36]
Hello,

I have this issue (1.4.1-rc2) :
```
[Vue warn]: Error in callback for watcher "value": "TypeError: _.deepExtend is not a function"
found in
---> <FormBuilder>
```

I checked with older version and the same error appears.

**Comment by sethsandaru** [comment]
Hi friend,

Vue-Form-Builder@2.0.0 has been released. Check it out.

P/s: I closed this issue because it's not related to Vue-Form-Builder@2.0.0
Thanks.
