### ISSUE TITLE
how we can add more controls

### ISSUE THREAD

**Issue by exiliensoft** [sethsandaru/vue-form-builder#37]
Hello Sandaru,

you had done amazing work thanks for this awesome code.

When we can get more control into it?
How we can add custom control as we required.

Thanks

**Comment by sethsandaru** [comment]
I'm writing the documentation for it at the moment. Stay tuned.

**Comment by sethsandaru** [comment]
Hi friend,

Vue-Form-Builder@2.0.0 has been released. Check it out.

P/s: I closed this issue because it's not related to Vue-Form-Builder@2.0.0
Thanks.
