### ISSUE TITLE
Error in callback for watcher "value": "TypeError: _.deepExtend is not a function"

### ISSUE THREAD

**Issue by liger800kg** [sethsandaru/vue-form-builder#40]
Hi. I have this issue :
![1](https://user-images.githubusercontent.com/5830591/87870491-355e7a80-c9b1-11ea-9594-1d988ccec239.png)
Please help!

**Comment by banunn** [comment]
Also having this issue. Is there a resolution yet?

**Comment by sethsandaru** [comment]
Hi friend,

Vue-Form-Builder@2.0.0 has been released. Check it out.

P/s: I closed this issue because it's not related to Vue-Form-Builder@2.0.0
Thanks.
