### ISSUE TITLE
Tabs support 

### ISSUE THREAD

**Issue by Diaskhan** [sethsandaru/vue-form-builder#43]
There any possibility to add tabs support ?

For example I want add 3 tabs.
And in each tab add 3 sections !

I have seen a couple form builders, the all without tabs support!

**Comment by sethsandaru** [comment]
Hi @Diaskhan ,

Thanks for the suggestion. Tab View is actually good and it always been in my head. But since we had 2 section views (normal & collapse-able), I couldn't see how I gonna design for the Tab View (structural, behaviour,...). I gotta think about it before I making it :D

**Comment by Diaskhan** [comment]
Its very simple! 
Every container must have children collection!
Childrens(item1, item2)

There must be a flag for container element!

Contatiner could have container inside !
