### ISSUE TITLE
Please close the current active sidebar before opening another

### ISSUE THREAD

**Issue by abhimanusharma** [sethsandaru/vue-form-builder#44]
Hi there,

I am getting "Please close the current active sidebar before opening another" toast error message even when sidebar is already closed.

**Comment by sethsandaru** [comment]
Hi friend,

IMO, it looks like a problem when we open/close the sidebar too fast and cost the EventBus an un-updated data. Could you try to save your form and try again? 

It would really nice if you can provide me some screenshots, video (from the beginning to the problem). 

Thanks

**Comment by sethsandaru** [comment]
There has been a week but no more detail/comment from you yet. I'll close this issue. Feel free to re-open it again with more information.

**Comment by abhimanusharma** [comment]
I think this happen when I opened a sidebar, then clicked on another setting icon, it keeps the state open of previous opened sidebar, now even if I close a sidebar, then the sidebar(config) I opened in the beginning have the state open/active. Same issue is on demo url of this package documentation.

**Comment by abhimanusharma** [comment]
@sethsandaru Hi, I am getting this error in the console. `https://www.loom.com/share/9005874690b74d49b5f37527dec8462b`

**Comment by sethsandaru** [comment]
Hello @abhimanusharma ,

Thanks for the info, let me check it.

**Comment by jomskidoodle** [comment]
![image](https://user-images.githubusercontent.com/2435077/101754638-eacfcd00-3b0e-11eb-831d-afad908ba38c.png)

I love this plugin exists, implemented it in nuxt and it looks great!
 I have a question though, do you guys any ways to handle this one?

And also, once the sidebar has been show, is there any way that I can close or exit the sidebar?

**Comment by sethsandaru** [comment]
Hi @jomskidoodle ,

Does your problem still around? Could you please create a new issue regarding your problem? (with all the information like your initialize code, your form structure,...)
