### ISSUE TITLE
styles.js is not setting default class for buttons generated by formbuilder

### ISSUE THREAD

**Issue by abhimanusharma** [sethsandaru/vue-form-builder#45]
Generated input text boxes are taking classes I set in plugin options as referenced in styles.js file.
but generated buttons are taking bootstrap classes by default.

**Comment by sethsandaru** [comment]
Hi friend,

You mean you want to use specific button classes instead of Bootstrap?

**Comment by sethsandaru** [comment]
There has been a week but no more detail/comment from you yet. I'll close this issue. Feel free to re-open it again with more information.
