### ISSUE TITLE
Error in created hook: "TypeError: Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by abhimanusharma** [sethsandaru/vue-form-builder#46]
When I load this on a modal using @click this error show in console. 

```
<FormBuilderModal
        :active="openAddFormDialog"
        :app="app"
        @dialogClose="handleDialogClose"
        ref="formBuilderModal"
        />
```
```
<md-button class="md-primary md-icon-button" @click="openAddFormDialog = true">
          <md-icon>add</md-icon>
</md-button>
```

**Comment by sethsandaru** [comment]
Hi friend,

Please provide the error on console, a full snippet of your component, where you are using the Vue Form Builder. Since the `FormBuilderModal` is not the Vue Form Builder' component.

For me, it looks like it's a problem from your internal project, not Vue Form Builder.

**Comment by sethsandaru** [comment]
There has been a week but no more detail yet. I'll close this issue. Feel free to re-open it again with more information.
