### ISSUE TITLE
Possibility for users to fill up certain groups multiple times

### ISSUE THREAD

**Issue by raphaelarias** [sethsandaru/vue-form-builder#47]
First of all, an outstanding package, congratulations.

Is it possible to do in the current package (or add to the package) a way for the users to fill up certain groups of fields multiple times?

For example, if we want to collect previous job experiences, we don't know how many they have. Something like this:

![image](https://user-images.githubusercontent.com/5008166/93279174-92e62c00-f794-11ea-9dbb-e2203535de16.png)

**Comment by sethsandaru** [comment]
Hello @raphaelarias ,

Thanks for the compliments. I very appreciate that.

In theory, it would be possible to fill up. I assume you have the data already, then just simply pass it to the `v-model` of Vue Form Builder. Therefore, the form will be filled up to certain fields based on your need.

Let me know if it can't work like that (also, more detail would be great)

Thanks.

**Comment by raphaelarias** [comment]
Hello @sethsandaru 

In this case, we don't have the data, but it would be nice to give the user the option to add this type of field, so when the end-user is filling up the form, they can click a + button to add more fields (or group of).

**Comment by sethsandaru** [comment]
Hello @raphaelarias ,

Ahh, I know what you want now. It's actually a feature from the Vue-Form-Builder@1.x.x (I called it as **Dynamic Section**) which basically let the users to +/- the same section to input more data. 

For @2.0.0 it hasn't had that feature yet. I'm still thinking of a good approach to make that happens. At least @2.2.0, it should be available.

Thanks.
