### ISSUE TITLE
Heads up on how to implement it?

### ISSUE THREAD

**Issue by digixweb** [sethsandaru/vue-form-builder#5]
I am new to Vue.js, so I am afraid I am missing some crucial understanding here. But how do you reference and use the forms in my own app? I am only able to setup the template/gui interface. So I can generate forms, and it outputs also some vue form data. But how do I integrate these form in my own app?

**Comment by sethsandaru** [comment]
Ah yeah. You need to know how the library works first.
- For Form Template, you will be able to create/config your own form. Set a variable for **v-model**. You will get a object of configurated form. And then you can save that object (parse to json string) into your DB.
- When you render Form GUI, get the configurated json string from your DB and then parse that string to object (JSON.parse), bind that object to **:form** and your form will be rendered. To get the form values that user typed, set a variable for **v-model**

For a good example, you can follow my example in this repo: https://github.com/sethsandaru/demo-vue-form-builder
