### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by VinceSanityyy** [sethsandaru/vue-form-builder#50]
There is no drag and drop functionality in the demo or in the UI

**Comment by abhimanusharma** [comment]
@VinceSanityyy  You can not drag and drop controls from sidebar to the section but you can drag and change the position of controls to move the to another section or exchange the position with another control of the same section.

**Comment by sethsandaru** [comment]
Hello @VinceSanityyy 

Please consider reading the documentation to see where's the drag and drop functionality you can use. Here is it: https://phattranminh96.gitbook.io/vue-form-builder/getting-started/form-builder-starter

P/s: @abhimanusharma thanks for your answer. You're right!!
