### ISSUE TITLE
Form Builder is not appearing in Laravel Nova Tool

### ISSUE THREAD

**Issue by vosaan** [sethsandaru/vue-form-builder#51]
Helo. I want to use your Form Builder with Laravel Nova Tool. My steps:
1. `npm i v-form-builder --save` 
2. My tool code:
```
<template>
    <div>
        <heading class="mb-6">Job Custom Forms</heading>

        <card class="flex flex-col items-center justify-center">
            <FormBuilder v-model="configuration"></FormBuilder>
        </card>
    </div>
</template>

<script>
    import FormBuilder from 'v-form-builder';

    export default {
        name: "JobCustomForms",
        components: {FormBuilder},
        data: () => ({
            configuration: {}
        })
    }
</script>
```
But page is still empty and no errors in console:
![Screenshot_3](https://user-images.githubusercontent.com/13124555/93857628-8f3a3400-fcc3-11ea-9ff4-6c46735252ff.jpg)

**Comment by abhimanusharma** [comment]
@vosaan Have you initiated the formbuilder plugin options in your main file correctly.

As mentioned in the documentation: https://phattranminh96.gitbook.io/vue-form-builder/getting-started/turning-up-the-form

```
import {VueFormBuilderPlugin} from 'v-form-builder'
import 'v-form-builder/dist/v-form-builder.css' //load CSS from your App

// install now
Vue.use(VueFormBuilderPlugin, options)
```

I think after this everything will work fine.

**Comment by vosaan** [comment]
I'm sorry. I'm new with Vue and Nova. So, I have only two files with JS in 'resources' folder:
1. tool.js with content
```
Nova.booting((Vue, router, store) => {
  router.addRoutes([
    {
      name: 'job-custom-forms',
      path: '/job-custom-forms',
      component: require('./components/Tool'),
    },
  ])
})
```
2. components/Tool.vue (content in my question)

In which one do I need to add the code?
![Screenshot_4](https://user-images.githubusercontent.com/13124555/93867191-5bfea180-fcd1-11ea-959e-b38fc3be1848.jpg)

**Comment by abhimanusharma** [comment]
@vosaan If you can share your code on git that will be very helpful to resolve your issue.

Try doing this in tool.js file

```
import {VueFormBuilderPlugin} from 'v-form-builder'
import 'v-form-builder/dist/v-form-builder.css' //load CSS from your App

Vue.use(VueFormBuilderPlugin, options);

Nova.booting((Vue, router, store) => {
  router.addRoutes([
    {
      name: 'job-custom-forms',
      path: '/job-custom-forms',
      component: require('./components/Tool'),
    },
  ])
})
```

Let me know if it resolve your problem.

**Comment by vosaan** [comment]
@abhimanusharma My attempts
1.
```
import { VueFormBuilderPlugin } from 'v-form-builder'
import 'v-form-builder/dist/v-form-builder.css' //load CSS from your App

Vue.use(VueFormBuilderPlugin);

Nova.booting((Vue, router, store) => {
  router.addRoutes([
    {
      name: 'job-custom-forms',
      path: '/job-custom-forms',
      component: require('./components/Tool'),
    },
  ]),
    VueFormBuilderPlugin
})
```
![Screenshot_5](https://user-images.githubusercontent.com/13124555/94115161-04d40a80-fe52-11ea-92f4-3fa1bbdec7b8.jpg)

2. 
```
import Vue from 'vue'
import { VueFormBuilderPlugin } from 'v-form-builder'
import 'v-form-builder/dist/v-form-builder.css' //load CSS from your App

Vue.use(VueFormBuilderPlugin);

Nova.booting((Vue, router, store) => {
  router.addRoutes([
    {
      name: 'job-custom-forms',
      path: '/job-custom-forms',
      component: require('./components/Tool'),
    },
  ]),
    VueFormBuilderPlugin
})
```
![Screenshot_6](https://user-images.githubusercontent.com/13124555/94115484-77dd8100-fe52-11ea-862c-079be0e2ddca.jpg)

> If you can share your code on git that will be very helpful to resolve your issue.

Ufortunately, I'm not owner of project so I can't share code

**Comment by abhimanusharma** [comment]
@vosaan Try this.

```
import Vue from 'vue'
import { VueFormBuilderPlugin } from 'v-form-builder'
import 'v-form-builder/dist/v-form-builder.css' //load CSS from your App

Nova.booting((Vue, router, store) => {
    Vue.use(VueFormBuilderPlugin);
    router.addRoutes([
    {
      name: 'job-custom-forms',
      path: '/job-custom-forms',
      component: require('./components/Tool'),
    },
  ]);
})
```

**Comment by vosaan** [comment]
Ufortunately result is the same like in my attempt number 2. I think this is a specific question of Laravel Nova. But I have one more Tool with "@fullcalendar/vue" component and it works fine. Anyway, thanks for your time

**Comment by sethsandaru** [comment]
@vosaan as @abhimanusharma said, it would be great if you could share with us your code (some little part of your application) which can be booted up and run it from our side. So I can personally dive into it and maybe can help you. I'm a Laravel-guy too but never work with Laravel Nova before :D

**Comment by sethsandaru** [comment]
It's been 3 days without any comments. I would like to close this issue. If you have any further detail or issue related to this, feel free to reopen it. Thanks
