### ISSUE TITLE
Is it possible to extend your component to add more controls

### ISSUE THREAD

**Issue by VasylDmytruk** [sethsandaru/vue-form-builder#6]
I would like to add new control "radio" (radio button). Also I would like to have possibility to change template of your controls, have possibility add label to input. Is it possible by extending (some how) your component?

**Comment by sethsandaru** [comment]
Noted your problem :D, currently I don't have any port to add custom control.
I'll try to see if I got any solution for this one :D

**Comment by sethsandaru** [comment]
I'll lock this issue, extend for more controls will be available in the next version :D
