### ISSUE TITLE
Disabling default component

### ISSUE THREAD

**Issue by abdullahcanakci** [sethsandaru/vue-form-builder#60]
Hi, is there any way to disable a default component so it won't show up in the builder?

**Comment by sethsandaru** [comment]
Hello @abdullahcanakci ,

Which components you are talking about? And why do you think it needs to be hidden?

**Comment by abdullahcanakci** [comment]
Hi @sethsandaru,
It's a general question, not for a particular component.

Let's say the user implemented a custom control instead of a regular one with extra logic or, functionc etc. instead of a regular one. It might be beneficial to show only one of them just for a use case.

The reason I'm interested in such feature is I implemented my own submit interaction outside of the form builder instance, with an external button with tapping into $formEvent eventbus. It has some extra logic. I can't be sure that form builders does this job well so I would like to remove button from builder so they can't mess with it.

**Comment by sethsandaru** [comment]
Hello @abdullahcanakci ,

Ah yes, I know what your idea now. Let me think for an approach. For now, you can make your own rules for your group and tell everybody doesn't touch to some specific components/controls.

Thanks

**Comment by abdullahcanakci** [comment]
Thanks, I'm happy that I made myself at least understandable.
That what my current approach will be actually and remove any non-wanted fields in the backend. 

Have a nice day :sun_with_face:

**Comment by sethsandaru** [comment]
I think I will close this because the Role-based permission is released in v2.1.0. Feel free to open it again.
