### ISSUE TITLE
Support for vue material

### ISSUE THREAD

**Issue by devla** [sethsandaru/vue-form-builder#61]
Hey bro!

How complicate would be to switch to vue material instead of bootstrap? Give me some suggestion, advice.

Thanks in advance,
Vladimir

**Comment by abhimanusharma** [comment]
@devla It is already available in v2.1.0, It will be available soon. See #49

**Comment by sethsandaru** [comment]
@abhimanusharma @devla  it's actually v2.0.1. And yes v2.0.1 is released. Please check it out.

Thanks
