### ISSUE TITLE
@2.1.0 development

### ISSUE THREAD

**Issue by sethsandaru** [sethsandaru/vue-form-builder#62]
Included so far:
- File Upload Control #55 
- Tabs View #43 
- Role-based Permissions for the Form

**Comment by sethsandaru** [comment]
Tabs View is ready.
Limitation: Should only use 1 tab view per form

**Comment by abhimanusharma** [comment]
Waiting for file attach/upload feature. ;)

**Comment by sethsandaru** [comment]
Role-based permission is ready too.

Now I'll go through the issues and fixing bugs (if any)

**Comment by sethsandaru** [comment]
#78 will be included

**Comment by sethsandaru** [comment]
v2.1.0 released. Thanks, everyone!

**Comment by JTrotta** [comment]
Is file upload control included?

**Comment by abhimanusharma** [comment]
@JTrotta Yes it is there now.

**Comment by JTrotta** [comment]
> @JTrotta Yes it is there now.

Cannot find in demo.
