### ISSUE TITLE
Question: Can we have a default submit button for generated form?

### ISSUE THREAD

**Issue by abhimanusharma** [sethsandaru/vue-form-builder#64]
Hi,

I see many users don't create a submit form and don't have a idea to put form action.

Can I set a default Form action and a submit button? 

By doing this the form will not only be limited for developers but any general user can create a form.

Or We can also make a validation so that a submit button and form action is required per form.

**Comment by sethsandaru** [comment]
Hi @abhimanusharma ,

From my beginning ideas of the Vue Form Builder, I don't want to depend on to the browser validation (like `<input required`). It's great to use the Validation built-in in the Vue Form Builder and we should use it. Let the JS does it jobs.

I don't know what is your approach for the `<form>`, but Vue Form Builder does offer you a way to wrap the `<form>...</form>` outside. Create a submit button is simple inside the Vue Form Builder also.

Thanks.
