### ISSUE TITLE
Datepicker not working on render

### ISSUE THREAD

**Issue by abhimanusharma** [sethsandaru/vue-form-builder#66]
This is the error in console.

```Error in callback for watcher "value": "TypeError: Cannot read property 'setDate' of null"

found in

---> <DatePickerControl>
       <ControlView>
         <NormalSectionView>```

**Comment by sethsandaru** [comment]
@abhimanusharma Could you share the steps to reproduce?

**Comment by abhimanusharma** [comment]
Fixed: The issue was causing due to setting default value for date property and formatted the date in particular format. After removing default value from form builder configuration, the error was gone.
