### ISSUE TITLE
Read only form renderer

### ISSUE THREAD

**Issue by abhimanusharma** [sethsandaru/vue-form-builder#67]
Hi,

We can save form builder configuration and render the form using saved configuration data. 
We can use v-model="formInput" to render the saved form data, but is it possible to make it read only. So that user can not update the value of form-Input.

```
<FormRenderer
            :form-configuration="formData"
            v-model="formInputData"
            readonly
    />
```

OR

```
<FormRenderer
            :form-configuration="formData"
            v-model="formInputData"
            :read-only="true"
    />
```

**Comment by sethsandaru** [comment]
Hi @abhimanusharma ,

Looks great. But I think I would like to do the "readonly/disable" like below:

```
methods: {
    disableField() {
        this.$formBuilder.disableField('field_unique_name');
    },
   enableField() {
        this.$formBuilder.enableField('field_unique_name');
   },
   enableAllFields() {
        this.$formBuilder.enableAllFields();
   },
   disableAllFields() {
        this.$formBuilder.disableAllFields();
   },
}
```

It would be more flexible for the Form Renderer too. Would add this one for @2.1.0.

Thanks

**Comment by abhimanusharma** [comment]
Awesome. Let's do this 🤩
