### ISSUE TITLE
Undefined message on validation error

### ISSUE THREAD

**Issue by abhimanusharma** [sethsandaru/vue-form-builder#69]
Hi,

When I have set validations (required) for few fields, instead of showing some message like *Fix errors before submitting* or something like this so that if there is a long form user can still see why isn't the form submitting instead I see an undefined message on the top right corner. 

See attached screenshot.
![Undefined error](https://user-images.githubusercontent.com/5707050/99032687-33dc4200-25a0-11eb-9d3b-f2fe01110bc9.png)

**Comment by sethsandaru** [comment]
Hi @abhimanusharma ,

I found out the problem. Basically, it's from here:

https://github.com/sethsandaru/vue-form-builder/blob/master/src/installer.js#L47

If you replaced the `properties` project when you're registering Vue Form Builder `Vue.use(..., {...})`. Then you need to add the `validationErrorAlertText` also. I forgot to `Object.assign` from the default one. But there won't be problem for @v2.1.0

Thanks.

**Comment by abhimanusharma** [comment]
Hi @sethsandaru , I have created a PR #70 for this issue. Please check it out.
