### ISSUE TITLE
submit form configuration

### ISSUE THREAD

**Issue by tqsoft** [sethsandaru/vue-form-builder#75]
hi
great form builer, really fully featured.

2 questions i have:
1. i haven't found in the doc how to submit the form configuration or how it create a json object i can use on my server side
2. is it possible to integrate signature pad plugin like https://www.npmjs.com/package/vue-signature-pad ?

**Comment by sethsandaru** [comment]
Hello @tqsoft ,

1. Please visit my documentation: https://phattranminh96.gitbook.io/vue-form-builder/getting-started/save-form-configuration or [this repository](https://github.com/sethsandaru/demo-vue-form-builder) to find out more how to save the JSON Form Configuration
2. Yes, you can follow this documentation page: [Create Custom Contro](https://phattranminh96.gitbook.io/vue-form-builder/extending/create-new-control).

Thanks. If you got any questions, feel free to open this issue again.
