### ISSUE TITLE
Copy/duplicate form control

### ISSUE THREAD

**Issue by abhimanusharma** [sethsandaru/vue-form-builder#76]
Can we expect the option to copy a control in a form builder section as there as many control fields which have mostly all information same. for example: first name and last name. all type, validations, classes for these form controls are same.

Just like this: https://formbuilder.online/

**Comment by sethsandaru** [comment]
Not sure in real life, we would really need to copy a whole Section? Many of my cases don't.

And also, we can't do that either because the fields need to have unique `key` names. 

I'll close this ticket then, thanks.

**Comment by abhimanusharma** [comment]
We can copy the section, For example if I want to show 4-5 textboxes in 7 sections, then copy section button should copy the section design and fields either leaving the unique fields like id and value empty or adding "fieldname-1" numeric after the existing name. This should be a must have feature in real life scenario, as while we are testing the form builder we some times need to copy the fields and sections many times. @sethsandaru
