### ISSUE TITLE
Getting error for regex validation

### ISSUE THREAD

**Issue by abhimanusharma** [sethsandaru/vue-form-builder#78]
Hi,

I am putting this regex for amount with decimal points. **\d+(\.\d{1,2})?**

I am getting this error.
![regex validation](https://user-images.githubusercontent.com/5707050/105331323-540c2b00-5bf9-11eb-9f74-2f10731abfce.png)

**Comment by sethsandaru** [comment]
@abhimanusharma Thanks, the reason is, I forgot to implement it :p.

Added it in v2.1.0
