### ISSUE TITLE
Validation regex not available

### ISSUE THREAD

**Issue by abdullahcanakci** [sethsandaru/vue-form-builder#80]
Hi,
I tried to set a regex validation on a field as per documentation. But I think either code or documentation is erronous on that matter.

There is a regex validation available on fields as per this ref.
https://github.com/sethsandaru/vue-form-builder/blob/b16f3e2d4436603c7f3089f3e8d45e3d24c50f4e/src/configs/validation.js#L40-L47

But because there is no corresponding branch here it throws an error.
https://github.com/sethsandaru/vue-form-builder/blob/b16f3e2d4436603c7f3089f3e8d45e3d24c50f4e/src/libraries/validation.js#L94-L115

like `Error in event handler for "renderer.run_validation": "TypeError: This validation type regex is not supported`

**Comment by abhimanusharma** [comment]
Copy of #78

**Comment by sethsandaru** [comment]
Thanks, v2.1.0 is released and added the regex validation. Documentation coming soon!
