### ISSUE TITLE
How translate elements

### ISSUE THREAD

**Issue by LucasPanetto** [sethsandaru/vue-form-builder#82]
Hello, I have doubts regarding the translation of the texts, I have not found material on this topic.

**Comment by LucasPanetto** [comment]
solved this problem by creating a fork of the project, and implementing the method responsible for translating texts from i18n, added the library to the project and created a new library of it all. Then, I imported this new library into my main project, and there I define the translation object.

**Comment by abhimanusharma** [comment]
@LucasPanetto Can you create a PR so that this feature can be included in the main project?

**Comment by LucasPanetto** [comment]
@abhimanusharma i can't make this now because that implementation require call i18n method in every local with texts. 
And now I'm waiting for definitions to finish the feature in my fork.

**Comment by loran750** [comment]
@LucasPanetto hello, I'm interested in that PR. How is your fork ? is it public ? I think vue-form-builder should be compliant with i18n. It would be so great

**Comment by LucasPanetto** [comment]
@loran750 hello.

My fork is private because I developed improvements on demand from my client, so it has a layout and sensitive rules.

In addition, I no longer have access to the code because I no longer serve this client.

But I tell you that it is not difficult to implement the i18n in the fork that you create.
