### ISSUE TITLE
Suggestion: use browser's datepicker for smaller bundle on supported browsers

### ISSUE THREAD

**Issue by raphaelarias** [sethsandaru/vue-form-builder#89]
Hi!

What a great package you have developed! I've starred it! You may have considered already, but perhaps it would be possible to remove datepicker dependency (for supported browsers) and use the browser's own date picker. Perhaps even allow the user to choose what datepicker they want.

Cheers!

**Comment by sethsandaru** [comment]
@raphaelarias This one actually was in my mind from the beginning of v2.0.0 (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) but IE9 & Safari can't use it and we might need to use a polyfill script (https://github.com/jcgertig/date-input-polyfill) ~35KB

Let's compare:

- https://bundlephobia.com/result?p=date-input-polyfill@2.14.0 
- https://bundlephobia.com/result?p=litepicker@1.4.6

So the litepicker is basically bigger than the polyfill a little bit (~1kb gzipped) but give us many great features.

😛

**Comment by sethsandaru** [comment]
I'd like to close this issue since there is no response. Let us keep using the Litepicker, it's super cool!
