### ISSUE TITLE
Is there a type="password" for input?

### ISSUE THREAD

**Issue by mingyuen78** [sethsandaru/vue-form-builder#90]
Is there a type="password" for input? i cant seem to find it. guess i have to change the json output later.

**Comment by abhimanusharma** [comment]
@mingyuen78 There is no such type by default but you can add custom control using documentation. [See Example](https://phattranminh96.gitbook.io/vue-form-builder/extending/create-new-control)

**Comment by sethsandaru** [comment]
@mingyuen78 @abhimanusharma I think it would be a good addition for `Text Input` control. 

Let me add it in #88
