### ISSUE TITLE
vuetify UI support

### ISSUE THREAD

**Issue by jomellelastrilla** [sethsandaru/vue-form-builder#98]
Is there a way that we can use or intergrate ui frameworks like vuetify in form renderer/builder?

**Comment by sethsandaru** [comment]
@jomellelastrilla I suppose Vue Form Builder should work fine for both Bootstrap and Material Design.

I think you can try to see, we did add some additional classes to support Material, thanks.

Feel free to open this again if there is anything unclear.

**Comment by karosaxy** [comment]
@jomellelastrilla please were you able to find a way to use vuetify framework?
